### ISSUE TITLE
Implementation of Fetch API

### ISSUE THREAD

**Issue by kevinm23nelson** [reesegreen2014/FitLit#3]
When I visit the FitLit application, I want to retrieve all my data for hydration and steps from online, so that I can keep track user data without having to have all the user data hardcoded into the application file.

Happy Path: My information will accurately be retrieved and fetched upon loading the page.
Sad Path: The information does not appear and a message pops up showing that there was an error of some kind.

**Comment by reesegreen2014** [comment]
Thanks for your work getting this fetch implemented, I appreciate it!!
